# -*- coding: utf-8 -*-
"""BTC .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ivcPDj5tUEiq4Ae09FLnq3-7NVHBu1op
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('/content/BTC.csv')
df.head()

df.shape

df.isnull().sum()

df.info()

from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression  # for Logistic Regression algorithm
from sklearn.model_selection import train_test_split #to split the dataset for training and testing
from sklearn import metrics #for checking the model accuracy
from sklearn.metrics import precision_score, recall_score, f1_score, roc_curve

df.head()

df.tail()

df.describe()

df['high'].mean()

def mean(A):
  sum = 0
  for i in A:
    sum+=i

  return sum/len(A)

df.corr()